services:
  weewx:
    image: felddy/weewx:latest
    container_name: weewx
    restart: unless-stopped
    env_file:
      - ../config/.env
    volumes:
      - ../data/weewx:/data
    networks:
      - lares

networks:
  lares:
    external: true
