apiVersion: 1

policies:
  - orgId: 1
    receiver: ntfy
    group_by: [alertname]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: pushover
        matchers:
          - receiver = pushover
        group_by: [alertname]
        group_wait: 30s
        repeat_interval: 24h
